[ui]
theme = "onedark"

[ui.input_bar]
prompt = " "

[ui.remote_control]
disabled = true

[ui.status_bar]
# hidden = true

[ui.theme_overrides]
# general
background = '#000000'
border_fg = 'bright-black'
# text_fg = ''
dimmed_text_fg = 'bright-white'
# input
input_text_fg = 'white'
result_count_fg = 'bright-black'
# results
result_name_fg = 'bright-black'
# result_line_number_fg = ''
# result_value_fg = ''
selection_fg = 'white'
selection_bg = 'black'
match_fg = 'bright-white'
# preview
preview_title_fg = 'bright-black'
# modes
action_picker_mode_bg = 'magenta'
action_picker_mode_fg = 'black'
channel_mode_bg = 'bright-black'
channel_mode_fg = 'black'
remote_control_mode_bg = 'green'
remote_control_mode_fg = 'black'
send_to_channel_mode_fg = 'cyan'
