[metadata]
name = "brew-packages"
description = "Browse homebrew packages"
requirements = ["brew"]

[source]
command = "{ brew formulae; brew casks } | sort"
frecency = false

[preview]
command = "HOMEBREW_COLOR=1 brew info '{}'"

# [ui]
# layout = "portrait"

[keybindings]
enter = "actions:open"

[actions.open]
description = "Installs brew package"
command = "brew install {}"
mode = "execute"
