[metadata]
name = "brew"
description = "Manage Homebrew packages"
requirements = ["brew"]

[source]
command = "{ brew leaves; brew list --casks } | sort"
frecency = false

[preview]
command = "HOMEBREW_COLOR=1 brew info '{}'"

# [ui]
# layout = "portrait"

[keybindings]
ctrl-u = "actions:upgrade"
ctrl-d = "actions:uninstall"

[actions.upgrade]
description = "Upgrade the selected package"
command = "brew upgrade {}"
mode = "execute"

[actions.uninstall]
description = "Uninstall the selected package"
command = "brew uninstall {}"
mode = "execute"
