[bar.default]
border_width = 1.0
center = [ "workspaces" ]
concave_edge_corners = false
end = [
    "tray",
    "cat",
    "clipboard",
    "network",
    "bluetooth",
    "brightness",
    "volume",
    "battery",
    "launcher",
    "notifications",
    "clock"
]
margin_edge = 0
margin_ends = 8
panel_overlap = 0
radius = 10
start = [ "control-center" ]
thickness = 26

    [bar.default.dead_zone.actions]
    scroll_down = "volume-down"
    scroll_up = "volume-up"

[brightness]
enable_ddcutil = true

[control_center]
sidebar = "full"
sidebar_section = "full"

[desktop_widgets]
enabled = false

[dock]
enabled = false

[location]
address = "Miami, FL"

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true

[nightlight]
enabled = true

[shell]
font_family = "Iosevka Aile"
polkit_agent = true
telemetry_enabled = true
time_format = "{:%-l:%M %p}"

    [shell.animation]
    speed = 4.0

    [shell.launcher]
    categories = false
    compact = true
    sort_by_usage = false

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    transparency_mode = "glass"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 5.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = "hyprshutdown -t \"Logging out…\""
    countdown_seconds = 5.0
    enabled = true
    shortcut = "i"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 5.0
    enabled = true
    label = "Suspend"
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = "hyprshutdown -t \"Restarting…\" --post-cmd \"reboot\""
    countdown_seconds = 5.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = "hyprshutdown -t \"Shutting down...\" --post-cmd \"shutdown -P 0\""
    countdown_seconds = 10.0
    enabled = true
    shortcut = "u"
    variant = "destructive"

[theme]
custom_palette = "mfd-amber"
source = "custom"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "kcolorscheme", "qt" ]
    community_ids = [ "hyprtoolkit" ]

[wallpaper]
enabled = false
fill_color = "#000000"
fill_mode = "center"

[weather]
unit = "imperial"

[widget.bluetooth]
enabled = false

[widget.brightness]
show_label = false

[widget.clipboard]
enabled = false

[widget.clock]
format = "{:%-l:%M %p}"
tooltip_format = "{:%a %b %e}  "

[widget.control-center]
glyph = "hyprland"

[widget.launcher]
enabled = true

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
enabled = false
show_label = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.workspaces]
display = "none"
focused_color = "secondary"
