mode = "dark"

accent = "#d97706" # amber-600
selection = "#451a03" # amber-950
selection_background = "#451a03" # amber-950
selection_foreground = "#d97706" # amber-600
muted = "#473c39" # taupe-700

background = "#0c0a09" # taupe-950
dark_background = "#0c0a09" # taupe-950
darker_background = "#0c0a09" # taupe-950
lighter_background = "#1d1816" # taupe-900

foreground = "#d97706" # amber-600
dark_foreground = "#b45309" # amber-700
light_foreground = "#fb923c" # orange-400
bright_foreground = "#f59e0b" # amber-500

red = "#dc2626" # red-600
yellow = "#d97706" # amber-600
orange = "#b45309" # amber-700
green = "#d97706" # amber-600
cyan = "#d97706" # amber-600
blue = "#d97706" # amber-600
magenta = "#d97706" # amber-600
brown = "#451a03" # amber-950

bright_red = "#ef4444" # red-500
bright_yellow = "#f59e0b" # amber-500
bright_green = "#10b981" # emerald-500
bright_cyan = "#f59e0b" # amber-500
bright_blue = "#f59e0b" # amber-500
bright_magenta = "#f59e0b" # amber-500
