[accessibility]
ui_scale = 1.0000000074505806

[bar.default]
background_opacity = 0.0
concave_edge_corners = false
end = [
    "media",
    "tray",
    "clipboard",
    "bluetooth",
    "network",
    "volume",
    "brightness",
    "notifications",
    "battery",
    "session"
]
margin_edge = 0
margin_ends = 2
padding = 4
radius = 2
start = [ "control-center", "workspaces", "active_window" ]
thickness = 24
widget_spacing = 8

    [bar.default.dead_zone.actions]
    scroll_down = "volume-down"
    scroll_up = "volume-up"

[brightness]
enable_ddcutil = true

[desktop_widgets]
enabled = false

[dock]
auto_hide = false
enabled = false
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 3600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    resume_command = "hyprctl dispatch dpms on"
    timeout = 660.0

[location]
address = "Miami, FL"
auto_locate = true

[lockscreen]
blurred_desktop = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@WAYLAND-1", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 540.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 6.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 3.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 287.0
    cy = 528.0
    output = "WAYLAND-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_night = 3000

[osd.kinds]
media = false

[plugins]
enabled = []

[shell]
corner_radius_scale = 0.2500000037252903
font_family = "Berkeley Mono Variable"
polkit_agent = true

    [shell.animation]
    enabled = false
    speed = 4.0

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher]
    categories = false
    compact = true
    sort_by_usage = false

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    open_near_click_wallpaper = true
    session_placement = "floating"
    wallpaper_placement = "floating"

    [shell.screenshot]
    clipboard = true
    save_to_file = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = "hyprshutdown || noctalia msg session logout"
    countdown_seconds = 5.0
    enabled = true
    shortcut = "o"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    label = "Suspend"
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = "hyprshutdown --post-cmd \"systemctl reboot\""
    countdown_seconds = 5.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = "hyprshutdown --post-cmd \"systemctl poweroff\""
    countdown_seconds = 0.0
    enabled = true
    shortcut = "u"
    variant = "destructive"

[theme]
community_palette = "Rosey AMOLED"
custom_palette = "mfd-nerv"
pure_black_dark = false
source = "custom"

    [theme.templates]
    builtin_ids = [ "hyprland" ]
    enable_community_templates = false

[wallpaper]
enabled = true
fill_color = "#100600"
fill_mode = "center"

    [wallpaper.default]
    path = "color:#1a0a00"

    [wallpaper.last]
    path = "color:#100600"

[weather]
unit = "imperial"

[widget.active_window]
capsule_foreground = "on_tertiary"
display = "text_only"
enabled = false
max_length = 800
min_length = 0
title_scroll = "on_hover"

[widget.brightness]
show_label = false

[widget.clock]
font_weight = 600
format = "{:%a %-l:%M %p}"
scale = 0.90000000000000002

[widget.control-center]
glyph = "hyprland"

[widget.media]
enabled = false
hide_album_art = true
hide_artist = true
hide_when_no_media = true
max_length = 400
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.taskbar]
only_active_workspace = true
show_window_title = true

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.workspaces]
empty_color = "primary"
focused_color = "secondary"
occupied_color = "primary"
style = "minimal"
