# ln ~/.config/starship.toml
format = """\
[╭╴](fg:arrow)\
$username\
$os\
$hostname\
$directory\
(\
    $git_branch\
    $git_status\
)\
$cmd_duration
[╰─](fg:arrow)$character\
"""
# Add the modules you need

# Disables the blank line at the start of the prompt
add_newline = true

palette = "adwaita-dark"

[palettes.adwaita-dark]
arrow = "#bac2de"
error = "#f38ba8"
user = "#89b4fa"
root = "#f38ba8"
os = "#cdd6f4"
directory = "#cba6f7"
time = "#FFDC72"
git = "#f9e2af"
git_status = "#94e2d5"
duration = "#74c7ec"
text_color = "#11111b"

[os]
format = "[](fg:os)[$symbol]($style)"
style = "bg:os fg:text_color"
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bg:os fg:text_color"
disabled = false

[username]
style_user = 'user'
style_root = 'root'
format = '[]($style)[ $user](bg:$style fg:text_color)[]($style) '
disabled = false
show_always = true

[character]
success_symbol = "[](fg:arrow)"
error_symbol = "[](fg:error)"
vimcmd_symbol = "[](fg:arrow)"

[directory]
format = " [](fg:directory)[  $path]($style)[$read_only]($read_only_style)[](fg:directory)"
truncation_length = 2
style = "fg:text_color bg:directory"
read_only_style = "fg:text_color bg:directory"
before_repo_root_style = "fg:text_color bg:directory"
read_only = "  "
truncate_to_repo = true
truncation_symbol = "…/"

[time]
disabled = true
format = " [](fg:time)[ $time]($style)[](fg:time)"
time_format = "%H:%M"
style = "fg:text_color bg:time"

[cmd_duration]
format = " [](fg:duration)[ $duration]($style)[](fg:duration)"
style = "fg:text_color bg:duration"
min_time = 5000

[git_branch]
format = " [](fg:git)[$symbol$branch](fg:text_color bg:git)[](fg:git)"
symbol = " "

[git_status]
format = '([ ](fg:git_status)[ $all_status$ahead_behind ]($style)[](fg:git_status))'
style = "fg:text_color bg:git_status"

[os.symbols]
Alpine = " "
AlmaLinux = " "
Amazon = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Kali = " "
Linux = " "
Macos = " "
NixOS = " "
Pop = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰨡 "
