[settings]
auto_update = true
env_file = ".env"
minimum_release_age = "0s"

[settings.ruby]

[settings.upgrade]
auto_prune = false

[tools]
claude = "latest"
cloudflared = "latest"
codex = "latest"
delta = "latest"
gh = "latest"
hunk = "latest"
node = "latest"
"npm:@opencode/cli" = { version = "latest", allow_builds = true, allow_low_downloads = true }
pi = "latest"
