[settings]
auto_update = true
env_file = ".env"
minimum_release_age = "0s"

[settings.ruby]
compile = true

[settings.upgrade]
auto_prune = false

[tools]
claude = "latest"
cloudflared = "latest"
codex = "latest"
delta = "latest"
gh = "latest"
"github:aloisdeniel/omafiles" = { version = "latest", os = ["linux"] }
"github:thisisgm/flea" = { version = "latest", os = ["linux"], bin_path = "target/release", strip_components = 1, postinstall = "cd \"$MISE_TOOL_INSTALL_PATH\" && ln -sfn /usr/share/omarchy/shell/Commons ui/Commons && ln -sfn /usr/share/omarchy/shell/Ui ui/Ui && mise x rust@stable -- cargo build --release --locked" }
hunk = "latest"
node = "latest"
pi = "latest"

[bootstrap.packages]
"brew:git" = "latest"
"brew:asdf" = "latest"
