[settings]
env_file = ".env"
minimum_release_age = "0s"

[settings.ruby]
compile = true

[settings.upgrade]
auto_prune = false

[tools]
codex = "latest"
delta = "latest"
hunk = "latest"
node = "latest"
pi = "latest"

[bootstrap.packages]
"brew:git" = "latest"
"brew:asdf" = "latest"
