# Makes hyprsunset do nothing to the screen by default
# Without this, the default applies some tint to the monitor
profile {
    time = 07:00
    identity = true
}

profile {
    time = 20:00
    temperature = 4000
}

profile {
    time = 23:59
    temperature = 3000
}
